<?php

namespace App\Http\Controllers;

use App\Models\Tarif;
use App\Models\Templete;
use App\Models\TempleteAnswer;
use App\Models\TempleteQuestion;
use App\Models\TempleteStartPage;
use Illuminate\Http\Request;
use Illuminate\Support\Str;
class TempleteController extends Controller
{
    public function createTarifs(){
       $tarifs = [
        [30, 80000],
        [100, 150000],
        [300, 300000],
        [500, 450000],
        [1000, 770000],
        [5000, 2300000],
       ];
        foreach ($tarifs as $key => $tarif) {
            $newtarif = new Tarif();
            $newtarif->leads = $tarif[0];
            $newtarif->price = $tarif[1];
            // $newtarif->save();
        }
        return response()->json(Tarif::all(),201);
    }
    public function createTemplete(){
        // $data = Templete::with('questions.answers')->get();
        // return response()->json($data);
        try {
            // Define themes and their specific questions
            $templates = [
                'Design' => [
                    'title' => 'Шаблон Дизайна',
                    'title_uz' => 'Dizayn Shabloni',
                    'meta_title' => 'Создайте уникальный дизайн',
                    'meta_title_uz' => 'Noyob dizayn yarating',
                    'meta_description' => 'Шаблон для дизайнеров и креативных студий.',
                    'meta_description_uz' => 'Dizaynerlar va kreativ studiyalar uchun shablon.',
                    'meta_favicon' => 'images/meta/favicon-design.png',
                    'meta_image' => 'images/meta/image-design.png',
                    'next_question_text' => 'Выберите стиль дизайна',
                    'next_question_text_uz' => 'Dizayn uslubini tanlang',
                    'next_to_form' => 'Перейти к оформлению дизайна',
                    'next_to_form_uz' => 'Dizaynni yaratishga o‘ting',
                    'start_page' => [
                        'hero_image' => 'images/design/hero.jpg',
                        'hero_image_mobi' => 'images/design/hero_mobile.jpg',
                        'logo' => 'images/design/logo.jpg',
                        'slogan_text' => 'Инновационный дизайн для современных потребностей',
                        'slogan_text_uz' => 'Zamonaviy ehtiyojlar uchun innovatsion dizayn',
                        'title' => 'Добро пожаловать в Дизайн Хаб',
                        'title_uz' => 'Dizayn markaziga xush kelibsiz',
                        'title_secondary' => 'Мы создаем впечатляющие дизайны',
                        'title_secondary_uz' => 'Biz ta’sirli dizaynlarni yaratamiz',
                        'button_text' => 'Начать проект',
                        'button_text_uz' => 'Loyihangizni boshlang',
                        'phoneNumber' => '+74951234567',
                        'phoneNumber_uz' => '+998123456789',
                        'companyName_text' => 'Дизайн агентство',
                        'companyName_text_uz' => 'Dizayn agentligi',
                        'design_type' => 0,
                        'design_alignment' => 0,
                    ],
                    'questions' => [
                    [
                        'type' => 'answer_options',
                        'question' => 'Какой стиль дизайна вам нравится?',
                        'question_uz' => 'Qaysi dizayn uslubi sizga yoqadi?',
                        'answers' => [
                            [
                                'image' => 'images/design/style-modern.jpg',
                                'text' => 'Современный стиль',
                                'text_uz' => 'Zamonaviy uslub',
                                'secondary_text' => 'Простота и минимализм с акцентом на функциональность',
                                'secondary_text_uz' => 'Soddalik va minimalizm, funksionallikka urg‘u beriladi',
                                'time_select' => now(),
                                'rank' => 1,
                                'rank_text_min' => 'Совсем не нравится',
                                'rank_text_min_uz' => 'Hech qachon yoqtirmayman',
                                'rank_text_max' => 'Очень нравится',
                                'rank_text_max_uz' => 'Juda yoqadi',
                            ],
                            [
                                'image' => 'images/design/style-classic.jpg',
                                'text' => 'Классический стиль',
                                'text_uz' => 'Klassik uslub',
                                'secondary_text' => 'Элегантность и традиции, придающие уверенность',
                                'secondary_text_uz' => 'Eleganslik va anʼanalar, ishonch uyg‘otadi',
                                'time_select' => now(),
                                'rank' => 2,
                                'rank_text_min' => 'Совсем не нравится',
                                'rank_text_min_uz' => 'Hech qachon yoqtirmayman',
                                'rank_text_max' => 'Очень нравится',
                                'rank_text_max_uz' => 'Juda yoqadi',
                            ],
                            [
                                'image' => 'images/design/style-industrial.jpg',
                                'text' => 'Индустриальный стиль',
                                'text_uz' => 'Sanoat uslubi',
                                'secondary_text' => 'Грубость и использование материалов в их естественном виде',
                                'secondary_text_uz' => 'Qattiqlik va materiallarning tabiiy holatida ishlatilishi',
                                'time_select' => now(),
                                'rank' => 3,
                                'rank_text_min' => 'Совсем не нравится',
                                'rank_text_min_uz' => 'Hech qachon yoqtirmayman',
                                'rank_text_max' => 'Очень нравится',
                                'rank_text_max_uz' => 'Juda yoqadi',
                            ],
                        ],
                    ],
                    [
                        'type' => 'answer_options',
                        'question' => 'Какие цвета вам наиболее привлекательны?',
                        'question_uz' => 'Qaysi ranglar sizni ko‘proq qiziqtiradi?',
                        'answers' => [
                            [
                                'image' => 'images/design/color-blue.jpg',
                                'text' => 'Синий',
                                'text_uz' => 'Ko‘k',
                                'secondary_text' => 'Цвет спокойствия и уверенности',
                                'secondary_text_uz' => 'Tinchlik va ishonch rangi',
                                'time_select' => now(),
                                'rank' => 1,
                                'rank_text_min' => 'Совсем не нравится',
                                'rank_text_min_uz' => 'Hech qachon yoqtirmayman',
                                'rank_text_max' => 'Очень нравится',
                                'rank_text_max_uz' => 'Juda yoqadi',
                            ],
                            [
                                'image' => 'images/design/color-red.jpg',
                                'text' => 'Красный',
                                'text_uz' => 'Qizil',
                                'secondary_text' => 'Цвет энергии и страсти',
                                'secondary_text_uz' => 'Energiya va ehtiros rangi',
                                'time_select' => now(),
                                'rank' => 2,
                                'rank_text_min' => 'Совсем не нравится',
                                'rank_text_min_uz' => 'Hech qachon yoqtirmayman',
                                'rank_text_max' => 'Очень нравится',
                                'rank_text_max_uz' => 'Juda yoqadi',
                            ],
                            [
                                'image' => 'images/design/color-green.jpg',
                                'text' => 'Зеленый',
                                'text_uz' => 'Yashil',
                                'secondary_text' => 'Цвет природы и гармонии',
                                'secondary_text_uz' => 'Tabiat va uyg‘unlik rangi',
                                'time_select' => now(),
                                'rank' => 3,
                                'rank_text_min' => 'Совсем не нравится',
                                'rank_text_min_uz' => 'Hech qachon yoqtirmayman',
                                'rank_text_max' => 'Очень нравится',
                                'rank_text_max_uz' => 'Juda yoqadi',
                            ],
                        ],
                    ],
                    [
                        'type' => 'answer_image',
                        'question' => 'Какую отделку вы предпочитаете?',
                        'question_uz' => 'Qaysi tugatish shaklini afzal ko‘rasiz?',
                        'answers' => [
                            [
                                'image' => 'images/design/finish-matte.jpg',
                                'text' => 'Матовая отделка',
                                'text_uz' => 'Mat rangi',
                                'secondary_text' => 'Покрытие, не отражающее свет, для классического вида',
                                'secondary_text_uz' => 'Yorug‘likni aks ettirmaydigan qoplama, klassik ko‘rinish uchun',
                                'time_select' => now(),
                                'rank' => 1,
                                'rank_text_min' => 'Совсем не нравится',
                                'rank_text_min_uz' => 'Hech qachon yoqtirmayman',
                                'rank_text_max' => 'Очень нравится',
                                'rank_text_max_uz' => 'Juda yoqadi',
                            ],
                            [
                                'image' => 'images/design/finish-glossy.jpg',
                                'text' => 'Глянцевая отделка',
                                'text_uz' => 'Yaltirashli qoplama',
                                'secondary_text' => 'Отражающие поверхности для современного стиля',
                                'secondary_text_uz' => 'Zamonaviy uslub uchun aks ettiruvchi yuzalar',
                                'time_select' => now(),
                                'rank' => 2,
                                'rank_text_min' => 'Совсем не нравится',
                                'rank_text_min_uz' => 'Hech qachon yoqtirmayman',
                                'rank_text_max' => 'Очень нравится',
                                'rank_text_max_uz' => 'Juda yoqadi',
                            ],
                            [
                                'image' => 'images/design/finish-textured.jpg',
                                'text' => 'Текстурированная отделка',
                                'text_uz' => 'To‘qimalangan qoplama',
                                'secondary_text' => 'Отделка с ощутимым рисунком, добавляющая оригинальности',
                                'secondary_text_uz' => 'Hissiyotli naqshga ega bo‘lgan qoplama, o‘ziga xoslik qo‘shadi',
                                'time_select' => now(),
                                'rank' => 3,
                                'rank_text_min' => 'Совсем не нравится',
                                'rank_text_min_uz' => 'Hech qachon yoqtirmayman',
                                'rank_text_max' => 'Очень нравится',
                                'rank_text_max_uz' => 'Juda yoqadi',
                            ],
                        ],
                    ],
                  ],
                ],
                'Buying a Car' => [
                    'title' => 'Покупка автомобиля',
                    'title_uz' => 'Avtomobil sotib olish',
                    'meta_title' => 'Узнайте больше о покупке автомобиля',
                    'meta_title_uz' => 'Avtomobil sotib olish haqida ko‘proq bilib oling',
                    'meta_description' => 'Шаблон для выбора и покупки автомобиля.',
                    'meta_description_uz' => 'Avtomobilni tanlash va sotib olish uchun shablon.',
                    'meta_favicon' => 'images/meta/favicon-car.png',
                    'meta_image' => 'images/meta/image-car.png',
                    'next_question_text' => 'Выберите предпочтения автомобиля',
                    'next_question_text_uz' => 'Avtomobilning afzalliklarini tanlang',
                    'next_to_form' => 'Перейти к форме покупки',
                    'next_to_form_uz' => 'Xarid qilish shakliga o‘ting',
                    'start_page' => [
                        'hero_image' => 'images/car/hero.jpg',
                        'hero_image_mobi' => 'images/car/hero_mobile.jpg',
                        'logo' => 'images/car/logo.jpg',
                        'slogan_text' => 'Drive Your Dreams',
                        'slogan_text_uz' => 'Orzularingizdagi haydovchiga aylaning',
                        'title' => 'Welcome to Car Finder',
                        'title_uz' => 'Avtomobil qidiruvchiga xush kelibsiz',
                        'title_secondary' => 'Choose the car that fits your lifestyle',
                        'title_secondary_uz' => 'Hayot tarzingizga mos keladigan avtomobilni tanlang',
                        'button_text' => 'Start Your Search',
                        'button_text_uz' => 'Qidiruvingizni boshlang',
                        'phoneNumber' => '+9876543210',
                        'phoneNumber_uz' => '+998987654321',
                        'companyName_text' => 'Car Finder Agency',
                        'companyName_text_uz' => 'Avtomobil qidiruv agentligi',
                        'design_type' => 0,
                        'design_alignment' => 2,
                    ],
                    'questions' => [
                        [
                            'type' => 'answer_image',
                            'question' => 'Какой тип автомобиля вам нужен?',
                            'question_uz' => 'Qaysi turdagi avtomobil kerak?',
                            'answers' => [
                                [
                                    'image' => 'images/cars/sedan.jpg',
                                    'text' => 'Седан',
                                    'text_uz' => 'Sedan',
                                    'secondary_text' => 'Идеальный для семейных поездок и комфортного путешествия',
                                    'secondary_text_uz' => 'Oilaviy sayohatlar va qulay sayohatlar uchun ideal',
                                    'time_select' => now(),
                                    'rank' => 1,
                                    'rank_text_min' => 'Совсем не нравится',
                                    'rank_text_min_uz' => 'Hech qachon yoqtirmayman',
                                    'rank_text_max' => 'Очень нравится',
                                    'rank_text_max_uz' => 'Juda yoqadi',
                                ],
                                [
                                    'image' => 'images/cars/suv.jpg',
                                    'text' => 'Внедорожник',
                                    'text_uz' => 'Yengil avtomobil',
                                    'secondary_text' => 'Для тех, кто ищет больше пространства и проходимости',
                                    'secondary_text_uz' => 'Ko‘proq joy va o‘tkazuvchanlikni izlayotganlar uchun',
                                    'time_select' => now(),
                                    'rank' => 2,
                                    'rank_text_min' => 'Совсем не нравится',
                                    'rank_text_min_uz' => 'Hech qachon yoqtirmayman',
                                    'rank_text_max' => 'Очень нравится',
                                    'rank_text_max_uz' => 'Juda yoqadi',
                                ],
                                [
                                    'image' => 'images/cars/coupe.jpg',
                                    'text' => 'Купе',
                                    'text_uz' => 'Kupe',
                                    'secondary_text' => 'Для любителей спортивного стиля и элегантности',
                                    'secondary_text_uz' => 'Sport uslubini va eleganslikni yoqtiradiganlar uchun',
                                    'time_select' => now(),
                                    'rank' => 3,
                                    'rank_text_min' => 'Совсем не нравится',
                                    'rank_text_min_uz' => 'Hech qachon yoqtirmayman',
                                    'rank_text_max' => 'Очень нравится',
                                    'rank_text_max_uz' => 'Juda yoqadi',
                                ],
                            ],
                        ],
                        [
                            'type' => 'answer_dropdown',
                            'question' => 'Какой бюджет у вас для покупки автомобиля?',
                            'question_uz' => 'Avtomobil sotib olish uchun byudjetingiz qancha?',
                            'answers' => [
                                [
                                    'image' => 'images/cars/budget-low.jpg',
                                    'text' => 'До 500,000 рублей',
                                    'text_uz' => '500,000 rubldan kam',
                                    'secondary_text' => 'Бюджет для экономичных автомобилей',
                                    'secondary_text_uz' => 'Tejamkor avtomobillar uchun byudjet',
                                    'time_select' => now(),
                                    'rank' => 1,
                                    'rank_text_min' => 'Совсем не нравится',
                                    'rank_text_min_uz' => 'Hech qachon yoqtirmayman',
                                    'rank_text_max' => 'Очень нравится',
                                    'rank_text_max_uz' => 'Juda yoqadi',
                                ],
                                [
                                    'image' => 'images/cars/budget-medium.jpg',
                                    'text' => '500,000 - 1,000,000 рублей',
                                    'text_uz' => '500,000 - 1,000,000 ruble',
                                    'secondary_text' => 'Средний бюджет для более качественных моделей',
                                    'secondary_text_uz' => 'Yuqori sifatli modellar uchun o‘rtacha byudjet',
                                    'time_select' => now(),
                                    'rank' => 2,
                                    'rank_text_min' => 'Совсем не нравится',
                                    'rank_text_min_uz' => 'Hech qachon yoqtirmayman',
                                    'rank_text_max' => 'Очень нравится',
                                    'rank_text_max_uz' => 'Juda yoqadi',
                                ],
                                [
                                    'image' => 'images/cars/budget-high.jpg',
                                    'text' => 'Более 1,000,000 рублей',
                                    'text_uz' => '1,000,000 rubledan ortiq',
                                    'secondary_text' => 'Высокий бюджет для премиум автомобилей',
                                    'secondary_text_uz' => 'Premium avtomobillar uchun yuqori byudjet',
                                    'time_select' => now(),
                                    'rank' => 3,
                                    'rank_text_min' => 'Совсем не нравится',
                                    'rank_text_min_uz' => 'Hech qachon yoqtirmayman',
                                    'rank_text_max' => 'Очень нравится',
                                    'rank_text_max_uz' => 'Juda yoqadi',
                                ],
                            ],
                        ],
                        [
                            'type' => 'answer_dropdown',
                            'question' => 'Какой год выпуска автомобиля вам предпочтителен?',
                            'question_uz' => 'Qaysi yil avtomobilni afzal ko‘rasiz?',
                            'answers' => [
                                [
                                    'image' => 'images/cars/year-2020.jpg',
                                    'text' => '2020 и новее',
                                    'text_uz' => '2020-yil va yangilari',
                                    'secondary_text' => 'Для тех, кто предпочитает новые автомобили',
                                    'secondary_text_uz' => 'Yangi avtomobillarni yoqtiradiganlar uchun',
                                    'time_select' => now(),
                                    'rank' => 1,
                                    'rank_text_min' => 'Совсем не нравится',
                                    'rank_text_min_uz' => 'Hech qachon yoqtirmayman',
                                    'rank_text_max' => 'Очень нравится',
                                    'rank_text_max_uz' => 'Juda yoqadi',
                                ],
                                [
                                    'image' => 'images/cars/year-2018.jpg',
                                    'text' => '2018-2020',
                                    'text_uz' => '2018-2020',
                                    'secondary_text' => 'Автомобили последних нескольких лет',
                                    'secondary_text_uz' => 'So‘nggi bir necha yillarda chiqarilgan avtomobillar',
                                    'time_select' => now(),
                                    'rank' => 2,
                                    'rank_text_min' => 'Совсем не нравится',
                                    'rank_text_min_uz' => 'Hech qachon yoqtirmayman',
                                    'rank_text_max' => 'Очень нравится',
                                    'rank_text_max_uz' => 'Juda yoqadi',
                                ],
                                [
                                    'image' => 'images/cars/year-2015.jpg',
                                    'text' => '2015-2018',
                                    'text_uz' => '2015-2018',
                                    'secondary_text' => 'Более доступные автомобили с хорошим состоянием',
                                    'secondary_text_uz' => 'Yaxshi holatda bo‘lgan, arzonroq avtomobillar',
                                    'time_select' => now(),
                                    'rank' => 3,
                                    'rank_text_min' => 'Совсем не нравится',
                                    'rank_text_min_uz' => 'Hech qachon yoqtirmayman',
                                    'rank_text_max' => 'Очень нравится',
                                    'rank_text_max_uz' => 'Juda yoqadi',
                                ],
                            ],
                        ],
                    ],
                ],
                'Tourism' => [
                    'title' => 'Туризм',
                    'title_uz' => 'Turizm',
                    'meta_title' => 'Откройте новые горизонты с нашим туристическим шаблоном',
                    'meta_title_uz' => 'Turistik shablonimiz bilan yangi ufqlarni kashf eting',
                    'meta_description' => 'Шаблон для планирования путешествий, отдыха и экскурсий.',
                    'meta_description_uz' => 'Sayohatlar, dam olish va ekskursiyalarni rejalashtirish uchun shablon.',
                    'meta_favicon' => 'images/meta/favicon-tourism.png',
                    'meta_image' => 'images/meta/image-tourism.png',
                    'next_question_text' => 'Выберите предпочтения для вашего путешествия',
                    'next_question_text_uz' => 'Sayohatingiz uchun afzalliklarni tanlang',
                    'next_to_form' => 'Перейти к форме бронирования',
                    'next_to_form_uz' => 'Buyurtma shakliga o‘ting',
                    'start_page' => [
                        'hero_image' => 'images/tourism/hero.jpg',
                        'hero_image_mobi' => 'images/tourism/hero_mobile.jpg',
                        'logo' => 'images/tourism/logo.jpg',
                        'slogan_text' => 'Исследуйте мир с нами',
                        'slogan_text_uz' => 'Biz bilan dunyoni o‘rganing',
                        'title' => 'Добро пожаловать в планировщик путешествий',
                        'title_uz' => 'Sayohat rejalashtiruvchiga xush kelibsiz',
                        'title_secondary' => 'Найдите лучшие направления и впечатления',
                        'title_secondary_uz' => 'Eng yaxshi sayohat manzillari va tajribalarni toping',
                        'button_text' => 'Начать планирование',
                        'button_text_uz' => 'Rejalashtirishni boshlang',
                        'phoneNumber' => '+9876543210',
                        'phoneNumber_uz' => '+998987654321',
                        'companyName_text' => 'Агентство туристических экспертов',
                        'companyName_text_uz' => 'Sayohat mutaxassislari agentligi',
                        'design_type' => 0,
                        'design_alignment' => 0,
                    ],
                    'questions' => [
                        [
                            'type' => 'answer_options',
                            'question' => 'Какой тип отдыха вам интересен?',
                            'question_uz' => 'Qaysi turdagi dam olishni izlayapsiz?',
                            'answers' => [
                                [
                                    'image' => 'images/tourism/beach.jpg',
                                    'text' => 'Пляжный отдых',
                                    'text_uz' => 'Plaj dam olishi',
                                    'secondary_text' => 'Идеально для тех, кто ищет расслабление и солнце',
                                    'secondary_text_uz' => 'Dam olish va quyoshni izlayotganlar uchun ideal',
                                    'time_select' => now(),
                                    'rank' => 1,
                                    'rank_text_min' => 'Совсем не нравится',
                                    'rank_text_min_uz' => 'Hech qachon yoqtirmayman',
                                    'rank_text_max' => 'Очень нравится',
                                    'rank_text_max_uz' => 'Juda yoqadi',
                                ],
                                [
                                    'image' => 'images/tourism/mountain.jpg',
                                    'text' => 'Горный туризм',
                                    'text_uz' => 'Tog‘ turizmi',
                                    'secondary_text' => 'Для любителей природы и активного отдыха',
                                    'secondary_text_uz' => 'Tabiat va faol dam olishni yoqtiradiganlar uchun',
                                    'time_select' => now(),
                                    'rank' => 2,
                                    'rank_text_min' => 'Совсем не нравится',
                                    'rank_text_min_uz' => 'Hech qachon yoqtirmayman',
                                    'rank_text_max' => 'Очень нравится',
                                    'rank_text_max_uz' => 'Juda yoqadi',
                                ],
                                [
                                    'image' => 'images/tourism/cultural.jpg',
                                    'text' => 'Культурный туризм',
                                    'text_uz' => 'Madaniy turizm',
                                    'secondary_text' => 'Для тех, кто хочет познакомиться с историей и культурой',
                                    'secondary_text_uz' => 'Tarix va madaniyat bilan tanishishni istaganlar uchun',
                                    'time_select' => now(),
                                    'rank' => 3,
                                    'rank_text_min' => 'Совсем не нравится',
                                    'rank_text_min_uz' => 'Hech qachon yoqtirmayman',
                                    'rank_text_max' => 'Очень нравится',
                                    'rank_text_max_uz' => 'Juda yoqadi',
                                ],
                            ],
                        ],
                        [
                            'type' => 'answer_options',
                            'question' => 'Какой бюджет вы планируете на отдых?',
                            'question_uz' => 'Dam olish uchun qancha byudjet tayyorladingiz?',
                            'answers' => [
                                [
                                    'image' => 'images/tourism/budget-low.jpg',
                                    'text' => 'До 50,000 рублей',
                                    'text_uz' => '50,000 rubldan kam',
                                    'secondary_text' => 'Для бюджетных поездок с экономным проживанием',
                                    'secondary_text_uz' => 'Tejamkor yashash joylari bilan byudjet sayohatlari uchun',
                                    'time_select' => now(),
                                    'rank' => 1,
                                    'rank_text_min' => 'Совсем не нравится',
                                    'rank_text_min_uz' => 'Hech qachon yoqtirmayman',
                                    'rank_text_max' => 'Очень нравится',
                                    'rank_text_max_uz' => 'Juda yoqadi',
                                ],
                                [
                                    'image' => 'images/tourism/budget-medium.jpg',
                                    'text' => '50,000 - 150,000 рублей',
                                    'text_uz' => '50,000 - 150,000 ruble',
                                    'secondary_text' => 'Средний бюджет для комфортного отдыха',
                                    'secondary_text_uz' => 'Qulay dam olish uchun o‘rtacha byudjet',
                                    'time_select' => now(),
                                    'rank' => 2,
                                    'rank_text_min' => 'Совсем не нравится',
                                    'rank_text_min_uz' => 'Hech qachon yoqtirmayman',
                                    'rank_text_max' => 'Очень нравится',
                                    'rank_text_max_uz' => 'Juda yoqadi',
                                ],
                                [
                                    'image' => 'images/tourism/budget-high.jpg',
                                    'text' => 'Более 150,000 рублей',
                                    'text_uz' => '150,000 rubledan ortiq',
                                    'secondary_text' => 'Для роскошных путешествий с высококлассным обслуживанием',
                                    'secondary_text_uz' => 'Yuqori sifatli xizmat ko‘rsatiladigan luks sayohatlar uchun',
                                    'time_select' => now(),
                                    'rank' => 3,
                                    'rank_text_min' => 'Совсем не нравится',
                                    'rank_text_min_uz' => 'Hech qachon yoqtirmayman',
                                    'rank_text_max' => 'Очень нравится',
                                    'rank_text_max_uz' => 'Juda yoqadi',
                                ],
                            ],
                        ],
                        [
                            'type' => 'answer_image',
                            'question' => 'Какую страну вы хотите посетить?',
                            'question_uz' => 'Qaysi mamlakatni ziyorat qilishni xohlaysiz?',
                            'answers' => [
                                [
                                    'image' => 'images/tourism/thailand.jpg',
                                    'text' => 'Таиланд',
                                    'text_uz' => 'Tailand',
                                    'secondary_text' => 'Страна с потрясающими пляжами и богатой культурой',
                                    'secondary_text_uz' => 'Ajoyib plyajlar va boy madaniyatga ega mamlakat',
                                    'time_select' => now(),
                                    'rank' => 1,
                                    'rank_text_min' => 'Совсем не нравится',
                                    'rank_text_min_uz' => 'Hech qachon yoqtirmayman',
                                    'rank_text_max' => 'Очень нравится',
                                    'rank_text_max_uz' => 'Juda yoqadi',
                                ],
                                [
                                    'image' => 'images/tourism/turkey.jpg',
                                    'text' => 'Турция',
                                    'text_uz' => 'Turkiya',
                                    'secondary_text' => 'Для тех, кто хочет сочетание пляжа и истории',
                                    'secondary_text_uz' => 'Plyaj va tarixni birlashtirishni istaganlar uchun',
                                    'time_select' => now(),
                                    'rank' => 2,
                                    'rank_text_min' => 'Совсем не нравится',
                                    'rank_text_min_uz' => 'Hech qachon yoqtirmayman',
                                    'rank_text_max' => 'Очень нравится',
                                    'rank_text_max_uz' => 'Juda yoqadi',
                                ],
                                [
                                    'image' => 'images/tourism/italy.jpg',
                                    'text' => 'Италия',
                                    'text_uz' => 'Italiya',
                                    'secondary_text' => 'Для любителей культуры и гастрономии',
                                    'secondary_text_uz' => 'Madaniyat va gastronomiyaga qiziqadiganlar uchun',
                                    'time_select' => now(),
                                    'rank' => 3,
                                    'rank_text_min' => 'Совсем не нравится',
                                    'rank_text_min_uz' => 'Hech qachon yoqtirmayman',
                                    'rank_text_max' => 'Очень нравится',
                                    'rank_text_max_uz' => 'Juda yoqadi',
                                ],
                            ],
                        ],
                    ],
                ],
                'Medicine' => [
                    'title' => 'Медицина',
                    'title_uz' => 'Tibbiyot',
                    'meta_title' => 'Доверяйте своему здоровью с нашим медицинским шаблоном',
                    'meta_title_uz' => 'Sog‘lig‘ingizni tibbiyot shablonimizga ishonib topshiring',
                    'meta_description' => 'Шаблон для выбора медицинских услуг, специалистов и клиник.',
                    'meta_description_uz' => 'Tibbiy xizmatlar, mutaxassislar va klinikalarni tanlash uchun shablon.',
                    'meta_favicon' => 'images/meta/favicon-medicine.png',
                    'meta_image' => 'images/meta/image-medicine.png',
                    'next_question_text' => 'Укажите предпочтения для медицинских услуг',
                    'next_question_text_uz' => 'Tibbiy xizmatlar uchun afzalliklaringizni kiriting',
                    'next_to_form' => 'Перейти к записи на прием',
                    'next_to_form_uz' => 'Qabulga yozilish shakliga o‘ting',
                    'questions' => [
                        [
                            'type' => 'answer_options',
                            'question' => 'Какой медицинский пакет вас интересует?',
                            'question_uz' => 'Qaysi tibbiy paketni tanlamoqchisiz?',
                            'answers' => [
                                [
                                    'image' => 'images/medicine/general-checkup.jpg',
                                    'text' => 'Общий медицинский осмотр',
                                    'text_uz' => 'Umumiy tibbiy tekshiruv',
                                    'secondary_text' => 'Для тех, кто хочет пройти регулярное обследование здоровья',
                                    'secondary_text_uz' => 'Sog‘liqni muntazam tekshirishni istaganlar uchun',
                                    'time_select' => now(),
                                    'rank' => 1,
                                    'rank_text_min' => 'Совсем не нравится',
                                    'rank_text_min_uz' => 'Hech qachon yoqtirmayman',
                                    'rank_text_max' => 'Очень нравится',
                                    'rank_text_max_uz' => 'Juda yoqadi',
                                ],
                                [
                                    'image' => 'images/medicine/specialist.jpg',
                                    'text' => 'Консультации с врачами-специалистами',
                                    'text_uz' => 'Mutaxassis shifokorlar bilan maslahatlashuv',
                                    'secondary_text' => 'Для диагностики и лечения конкретных заболеваний',
                                    'secondary_text_uz' => 'Maxsus kasalliklarni aniqlash va davolash uchun',
                                    'time_select' => now(),
                                    'rank' => 2,
                                    'rank_text_min' => 'Совсем не нравится',
                                    'rank_text_min_uz' => 'Hech qachon yoqtirmayman',
                                    'rank_text_max' => 'Очень нравится',
                                    'rank_text_max_uz' => 'Juda yoqadi',
                                ],
                                [
                                    'image' => 'images/medicine/surgery.jpg',
                                    'text' => 'Хирургическое вмешательство',
                                    'text_uz' => 'Jarrohlik aralashuvi',
                                    'secondary_text' => 'Для пациентов, которым требуется операция',
                                    'secondary_text_uz' => 'Amaliyotga muhtoj bo‘lgan bemorlar uchun',
                                    'time_select' => now(),
                                    'rank' => 3,
                                    'rank_text_min' => 'Совсем не нравится',
                                    'rank_text_min_uz' => 'Hech qachon yoqtirmayman',
                                    'rank_text_max' => 'Очень нравится',
                                    'rank_text_max_uz' => 'Juda yoqadi',
                                ],
                            ],
                        ],
                        [
                            'type' => 'answer_options',
                            'question' => 'Какой срок лечения вас устраивает?',
                            'question_uz' => 'Davolanish muddati sizni qoniqtiradimi?',
                            'answers' => [
                                [
                                    'image' => 'images/medicine/short-term.jpg',
                                    'text' => 'Краткосрочное лечение',
                                    'text_uz' => 'Qisqa muddatli davolanish',
                                    'secondary_text' => 'Для несложных заболеваний, требующих короткого времени на восстановление',
                                    'secondary_text_uz' => 'Oddiy kasalliklar uchun, tiklanish uchun qisqa vaqt kerak',
                                    'time_select' => now(),
                                    'rank' => 1,
                                    'rank_text_min' => 'Совсем не нравится',
                                    'rank_text_min_uz' => 'Hech qachon yoqtirmayman',
                                    'rank_text_max' => 'Очень нравится',
                                    'rank_text_max_uz' => 'Juda yoqadi',
                                ],
                                [
                                    'image' => 'images/medicine/long-term.jpg',
                                    'text' => 'Долгосрочное лечение',
                                    'text_uz' => 'Uzun muddatli davolanish',
                                    'secondary_text' => 'Для более сложных заболеваний, требующих длительного восстановления',
                                    'secondary_text_uz' => 'Qiyinroq kasalliklar uchun, uzoq tiklanish davri talab qilinadi',
                                    'time_select' => now(),
                                    'rank' => 2,
                                    'rank_text_min' => 'Совсем не нравится',
                                    'rank_text_min_uz' => 'Hech qachon yoqtirmayman',
                                    'rank_text_max' => 'Очень нравится',
                                    'rank_text_max_uz' => 'Juda yoqadi',
                                ],
                            ],
                        ],
                        [
                            'type' => 'answer_rank',
                            'question' => 'Какой вид медицинских услуг вам необходим?',
                            'question_uz' => 'Qaysi tibbiy xizmatlar sizga zarur?',
                            'answers' => [
                                [
                                    'image' => 'images/medicine/dental-care.jpg',
                                    'text' => 'Стоматологическая помощь',
                                    'text_uz' => 'Stomatologik yordam',
                                    'secondary_text' => 'Для лечения зубов и профилактики заболеваний полости рта',
                                    'secondary_text_uz' => 'Tishlarni davolash va og‘iz bo‘shlig‘i kasalliklarini oldini olish',
                                    'time_select' => now(),
                                    'rank' => 1,
                                    'rank_text_min' => 'Совсем не нравится',
                                    'rank_text_min_uz' => 'Hech qachon yoqtirmayman',
                                    'rank_text_max' => 'Очень нравится',
                                    'rank_text_max_uz' => 'Juda yoqadi',
                                ],
                                
                            ],
                        ],
                    ],
                    'start_page' => [
                        'hero_image' => 'images/medicine/hero.jpg',
                        'hero_image_mobi' => 'images/medicine/hero_mobile.jpg',
                        'logo' => 'images/medicine/logo.jpg',
                        'slogan_text' => 'Ваше здоровье - наша забота',
                        'slogan_text_uz' => 'Sog‘lig‘ingiz - bizning g‘amxo‘rligimiz',
                        'title' => 'Добро пожаловать в наш медицинский центр',
                        'title_uz' => 'Bizning tibbiy markazimizga xush kelibsiz',
                        'title_secondary' => 'Мы заботимся о вашем здоровье',
                        'title_secondary_uz' => 'Biz sizning sog‘lig‘ingiz haqida qayg‘uramiz',
                        'button_text' => 'Узнать больше',
                        'button_text_uz' => 'Ko‘proq bilib oling',
                        'phoneNumber' => '+9876543210',
                        'phoneNumber_uz' => '+998987654321',
                        'companyName_text' => 'Медицинский центр надежды',
                        'companyName_text_uz' => 'Umid tibbiyot markazi',
                        'design_type' => 0,
                        'design_alignment' => 2,
                    ],
                ],
                'Learning Center' => [
                    'title' => 'Образовательный центр',
                    'title_uz' => 'O‘quv markazi',
                    'meta_title' => 'Найдите идеальный образовательный центр для ваших нужд',
                    'meta_title_uz' => 'O‘quv ehtiyojlaringiz uchun mukammal markazni toping',
                    'meta_description' => 'Шаблон для поиска курсов, образовательных центров и программ обучения.',
                    'meta_description_uz' => 'Kurslar, o‘quv markazlari va o‘quv dasturlarini topish uchun shablon.',
                    'meta_favicon' => 'images/meta/favicon-learning.png',
                    'meta_image' => 'images/meta/image-learning.png',
                    'next_question_text' => 'Выберите предпочтения для образовательного центра',
                    'next_question_text_uz' => 'O‘quv markazi uchun afzalliklaringizni tanlang',
                    'next_to_form' => 'Перейти к записи на курсы',
                    'next_to_form_uz' => 'Kurslarga yozilish shakliga o‘ting',
                    'start_page' => [
                        'hero_image' => 'images/learning-center/hero.jpg',
                        'hero_image_mobi' => 'images/learning-center/hero_mobile.jpg',
                        'logo' => 'images/learning-center/logo.jpg',
                        'slogan_text' => 'Образование для будущего',
                        'slogan_text_uz' => 'Kelajak uchun taʼlim',
                        'title' => 'Добро пожаловать в образовательный центр',
                        'title_uz' => 'Taʼlim markaziga xush kelibsiz',
                        'title_secondary' => 'Мы помогаем вам учиться лучше',
                        'title_secondary_uz' => 'Biz sizga yaxshiroq o‘rganishga yordam beramiz',
                        'button_text' => 'Начать обучение',
                        'button_text_uz' => 'Taʼlimni boshlash',
                        'phoneNumber' => '+123456789',
                        'phoneNumber_uz' => '+998123456789',
                        'companyName_text' => 'Образовательный центр знаний',
                        'companyName_text_uz' => 'Bilim taʼlim markazi',
                        'design_type' => 1,
                        'design_alignment' => 0,
                    ],
                    'questions' => [
                        [
                            'type' => 'answer_options',
                            'question' => 'Какие учебные курсы вам интересны?',
                            'question_uz' => 'Qaysi o‘quv kurslari sizni qiziqtiradi?',
                            'answers' => [
                                [
                                    'image' => 'images/learning/programming.jpg',
                                    'text' => 'Программирование и разработка',
                                    'text_uz' => 'Dasturlash va ishlab chiqish',
                                    'secondary_text' => 'Для тех, кто хочет изучать создание веб-приложений и программного обеспечения',
                                    'secondary_text_uz' => 'Veb-ilovalar va dasturiy ta’minot yaratishni o‘rganmoqchi bo‘lganlar uchun',
                                    'time_select' => now(),
                                    'rank' => 1,
                                    'rank_text_min' => 'Совсем не нравится',
                                    'rank_text_min_uz' => 'Hech qachon yoqtirmayman',
                                    'rank_text_max' => 'Очень нравится',
                                    'rank_text_max_uz' => 'Juda yoqadi',
                                ],
                                [
                                    'image' => 'images/learning/marketing.jpg',
                                    'text' => 'Маркетинг и реклама',
                                    'text_uz' => 'Marketing va reklama',
                                    'secondary_text' => 'Для тех, кто хочет изучать принципы маркетинга и рекламы в различных сферах',
                                    'secondary_text_uz' => 'Turli sohalarda marketing va reklama tamoyillarini o‘rganmoqchi bo‘lganlar uchun',
                                    'time_select' => now(),
                                    'rank' => 2,
                                    'rank_text_min' => 'Совсем не нравится',
                                    'rank_text_min_uz' => 'Hech qachon yoqtirmayman',
                                    'rank_text_max' => 'Очень нравится',
                                    'rank_text_max_uz' => 'Juda yoqadi',
                                ],
                                [
                                    'image' => 'images/learning/management.jpg',
                                    'text' => 'Менеджмент и лидерство',
                                    'text_uz' => 'Menejment va liderlik',
                                    'secondary_text' => 'Для тех, кто хочет развить навыки управления и лидерства',
                                    'secondary_text_uz' => 'Boshqaruv va liderlik ko‘nikmalarini rivojlantirmoqchi bo‘lganlar uchun',
                                    'time_select' => now(),
                                    'rank' => 3,
                                    'rank_text_min' => 'Совсем не нравится',
                                    'rank_text_min_uz' => 'Hech qachon yoqtirmayman',
                                    'rank_text_max' => 'Очень нравится',
                                    'rank_text_max_uz' => 'Juda yoqadi',
                                ],
                            ],
                        ],
                        [
                            'type' => 'answer_options',
                            'question' => 'Какой формат обучения вам подходит?',
                            'question_uz' => 'Qanday o‘quv formati sizga mos?',
                            'answers' => [
                                [
                                    'image' => 'images/learning/online.jpg',
                                    'text' => 'Онлайн обучение',
                                    'text_uz' => 'Onlayn o‘qish',
                                    'secondary_text' => 'Для тех, кто предпочитает учиться в любое время и в любом месте',
                                    'secondary_text_uz' => 'Istalgan vaqtda va istalgan joyda o‘qishni afzal ko‘radiganlar uchun',
                                    'time_select' => now(),
                                    'rank' => 1,
                                    'rank_text_min' => 'Совсем не нравится',
                                    'rank_text_min_uz' => 'Hech qachon yoqtirmayman',
                                    'rank_text_max' => 'Очень нравится',
                                    'rank_text_max_uz' => 'Juda yoqadi',
                                ],
                                [
                                    'image' => 'images/learning/classroom.jpg',
                                    'text' => 'Очные занятия',
                                    'text_uz' => 'Yuzma-yuz darslar',
                                    'secondary_text' => 'Для тех, кто предпочитает традиционное обучение с преподавателем',
                                    'secondary_text_uz' => 'Ustoz bilan an’anaviy o‘qishni afzal ko‘radiganlar uchun',
                                    'time_select' => now(),
                                    'rank' => 2,
                                    'rank_text_min' => 'Совсем не нравится',
                                    'rank_text_min_uz' => 'Hech qachon yoqtirmayman',
                                    'rank_text_max' => 'Очень нравится',
                                    'rank_text_max_uz' => 'Juda yoqadi',
                                ],
                            ],
                        ],
                        [
                            'type' => 'answer_options',
                            'question' => 'Какое время обучения вам удобно?',
                            'question_uz' => 'Qaysi o‘quv vaqti sizga qulay?',
                            'answers' => [
                                [
                                    'image' => 'images/learning/morning.jpg',
                                    'text' => 'Утренние занятия',
                                    'text_uz' => 'Ertalabki darslar',
                                    'secondary_text' => 'Для тех, кто хочет начать день с обучения',
                                    'secondary_text_uz' => 'Kuni ertalab o‘qishni boshlashni afzal ko‘radiganlar uchun',
                                    'time_select' => now(),
                                    'rank' => 1,
                                    'rank_text_min' => 'Совсем не нравится',
                                    'rank_text_min_uz' => 'Hech qachon yoqtirmayman',
                                    'rank_text_max' => 'Очень нравится',
                                    'rank_text_max_uz' => 'Juda yoqadi',
                                ],
                                [
                                    'image' => 'images/learning/evening.jpg',
                                    'text' => 'Вечерние занятия',
                                    'text_uz' => 'Kecha darslari',
                                    'secondary_text' => 'Для тех, кто предпочитает учиться вечером после работы',
                                    'secondary_text_uz' => 'Ishdan keyin kechqurun o‘qishni afzal ko‘radiganlar uchun',
                                    'time_select' => now(),
                                    'rank' => 2,
                                    'rank_text_min' => 'Совсем не нравится',
                                    'rank_text_min_uz' => 'Hech qachon yoqtirmayman',
                                    'rank_text_max' => 'Очень нравится',
                                    'rank_text_max_uz' => 'Juda yoqadi',
                                ],
                            ],
                        ],
                    ],
                ],
            ];
    
            // Create templates and associate them with questions and answers
            foreach ($templates as $theme => $data) {
                $template = Templete::create([
                    'title' => $data['title'],
                    'title_uz' => $data['title_uz'],
                    'category_id' => null,
                    
                   
                    'meta_title' => $data['title'] . ' метаданные',
                    'meta_title_uz' => $data['title_uz'] . ' Metadata',
                    'meta_description' => 'Описание ' . $data['title'],
                    'meta_description_uz' => $data['title_uz'] . ' haqida tasnifi',
                    'meta_favicon' => $data['meta_favicon'],
                    'meta_image' => $data['meta_image'],
                    'next_question_text' => 'Что дальше?',
                    'next_question_text_uz' => 'Keyingisi nima?',
                    'next_to_form' => 'Продолжить к форме',
                    'next_to_form_uz' => 'Shaklga davom eting',
                    
                ]);
                $startPageData = $data['start_page'];
                TempleteStartPage::create([
                    'templete_id' => $template->id,
                    'hero_image' => $startPageData['hero_image'],
                    'hero_image_mobi' => $startPageData['hero_image_mobi'],
                    'logo' => $startPageData['logo'],
                    'slogan_text' => $startPageData['slogan_text'],
                    'slogan_text_uz' => $startPageData['slogan_text_uz'],
                    'title' => $startPageData['title'],
                    'title_uz' => $startPageData['title_uz'],
                    'title_secondary' => $startPageData['title_secondary'],
                    'title_secondary_uz' => $startPageData['title_secondary_uz'],
                    'button_text' => $startPageData['button_text'],
                    'button_text_uz' => $startPageData['button_text_uz'],
                    'phoneNumber' => $startPageData['phoneNumber'],
                    'phoneNumber_uz' => $startPageData['phoneNumber_uz'],
                    'companyName_text' => $startPageData['companyName_text'],
                    'companyName_text_uz' => $startPageData['companyName_text_uz'],
                    'design_type' => $startPageData['design_type'],
                    'design_alignment' => $startPageData['design_alignment'],
                ]);
                foreach ($data['questions'] as $questionData) {
                    $question = TempleteQuestion::create([
                        'templete_id' => $template->id,
                        'type' => $questionData['type'],
                        'question' => $questionData['question'],
                        'question_uz' => $questionData['question_uz'],
                    ]);
    
                    foreach ($questionData['answers'] as $answerData) {
                        TempleteAnswer::create([
                            'templete_questions_id' => $question->id,
                            'text' => $answerData['text'],
                            'text_uz' => $answerData['text_uz'],
                            'image' => $answerData['image'], // Assuming image is part of $answerData
                            'secondary_text' => $answerData['secondary_text'],
                            'secondary_text_uz' => $answerData['secondary_text_uz'],
                            'time_select' => $answerData['time_select'],
                            'rank' => $answerData['rank'],
                            'rank_text_min' => $answerData['rank_text_min'],
                            'rank_text_min_uz' => $answerData['rank_text_min_uz'],
                            'rank_text_max' => $answerData['rank_text_max'],
                            'rank_text_max_uz' => $answerData['rank_text_max_uz'],
                        ]);
                    }
                }
            }
    
            return response()->json(['message' => 'Templates created successfully'], 201);
        } catch (\Exception $e) {
            return response()->json(['error' => $e->getMessage()], 500);
        }
    }
}
